/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'Nikolay' at '03.09.13 0:22' with Gradle 1.7
 *
 * @author Nikolay, @date 03.09.13 0:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
